# These are supported funding model platforms

# GitHub Sponsors (replace with your GitHub username)
# github: [bitcode]

# Open Collective (replace with your Open Collective username)
# open_collective: arm-assembly-university

# Ko-fi (replace with your Ko-fi username)
# ko_fi: arm_assembly_university

# Tidelift (replace with your Tidelift package name)
# tidelift: npm/arm-assembly-university

# Community Bridge (replace with your project name)
# community_bridge: arm-assembly-university

# Liberapay (replace with your Liberapay username)
# liberapay: arm-assembly-university

# IssueHunt (replace with your IssueHunt username)
# issuehunt: bitcode

# Otechie (replace with your Otechie username)
# otechie: bitcode

# LFX Crowdfunding (replace with your project name)
# lfx_crowdfunding: arm-assembly-university

# Custom funding URLs (uncomment and replace with your funding URLs)
# custom: ['https://www.paypal.me/armassemblyuniversity', 'https://buy-me-a-coffee.com/armassembly']

# Educational Project Notice
# This is an educational open-source project focused on ARM AArch64 assembly language learning.
# Funding helps support:
# - Course content development and maintenance
# - Community platform hosting and tools
# - Educational resource creation
# - Student support and mentorship programs
# - Technical infrastructure and testing environments
