name: 🐛 Bug Report
description: Report a bug in course materials, exercises, or documentation
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! This helps improve the course for everyone.
        
  - type: dropdown
    id: bug-category
    attributes:
      label: Bug Category
      description: What type of content has the bug?
      options:
        - Course Documentation
        - Exercise Code
        - Module Content
        - Build/Compilation Issues
        - Website/Repository
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which module is affected?
      options:
        - M1 - Foundation
        - M2 - Data & Registers
        - M3 - Basic Instruction Set
        - M4 - Memory & Data Structures
        - M5 - Control Flow & Structure
        - M6 - Advanced Features
        - M7 - Optimization & Debugging
        - General/Multiple Modules
        - Not Module Specific
    validations:
      required: true

  - type: input
    id: file-path
    attributes:
      label: File Path
      description: Path to the file with the bug (if applicable)
      placeholder: "e.g., modules/m1-foundation/exercises/1.1-hello-beginner.s"
    validations:
      required: false

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to...
        2. Compile/Run...
        3. See error...
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Development Environment
      description: What environment are you using?
      options:
        - Linux (x86_64)
        - Linux (ARM64)
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Windows (WSL)
        - Windows (Native)
        - Docker Container
        - Other
    validations:
      required: true

  - type: input
    id: toolchain-version
    attributes:
      label: Toolchain Version
      description: Version of GCC, assembler, or other tools
      placeholder: "e.g., gcc version 11.4.0, GNU assembler 2.38"
    validations:
      required: false

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Any error messages or unexpected output
      render: shell
    validations:
      required: false

  - type: dropdown
    id: difficulty-level
    attributes:
      label: Your Experience Level
      description: This helps us understand the context
      options:
        - Beginner (new to assembly)
        - Intermediate (some assembly experience)
        - Advanced (experienced with assembly)
        - Expert (professional assembly developer)
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided clear steps to reproduce the issue
          required: true
        - label: I have included relevant error messages or output
          required: false
